vagrant_hostname: local.bruins19.com
vagrant_machine_name: bruins19
vagrant_ip: 192.168.225.252
vagrant_box: geerlingguy/ubuntu1604
workspace: /root
drupal_site_name: 'BLTed 10'
vagrant_synced_folders:
    -
        local_path: .
        destination: /var/www/bruins19
        type: nfs
drupal_build_composer_project: false
drupal_composer_path: false
drupal_composer_install_dir: /var/www/bruins19
drupal_core_path: /var/www/bruins19/docroot
ssh_home: /var/www/bruins19
apache_vhosts:
    -
        servername: '{{ drupal_domain }}'
        serveralias: 'www.{{ drupal_domain }}'
        documentroot: '{{ drupal_core_path }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: 'dashboard.{{ drupal_domain }}'
        serveralias: 'www.dashboard.{{ drupal_domain }}'
        documentroot: /var/www/dashboard
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: local.feltonsite.com
        documentroot: '{{ drupal_core_path }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
    -
        servername: local.quinn.com
        documentroot: '{{ drupal_core_path }}'
        extra_parameters: '{{ apache_vhost_php_fpm_parameters }}'
mysql_databases:
    -
        name: drupal
        encoding: utf8mb4
        collation: utf8mb4_general_ci
    -
        name: drupal_feltonsite
        encoding: utf8mb4
        collation: utf8mb4_general_ci
    -
        name: drupal_quinn
        encoding: utf8mb4
        collation: utf8mb4_general_ci
mysql_users:
    -
        name: drupal
        host: '%'
        password: drupal
        priv: 'drupal%.*:ALL'
    -
        name: drupal
        host: '%'
        password: drupal
        priv: 'drupal_feltonsite%.*:ALL'
    -
        name: drupal
        host: '%'
        password: drupal
        priv: 'drupal_quinn%.*:ALL'
drupal_install_site: false
configure_drush_aliases: false
extra_packages:
    - patchutils
    - sqlite
installed_extras:
    - adminer
    - drush
php_version: '7.2'
php_packages_extra:
    - 'php{{ php_version }}-bz2'
    - 'php{{ php_version }}-imagick'
    - imagemagick
php_xdebug_version: 2.7.1
php_xdebug_default_enable: 0
php_xdebug_cli_disable: 'yes'
php_xdebug_remote_port: '9000'
php_memory_limit: 512M
solr_version: 4.5.1
post_provision_scripts:
    - ../../../acquia/blt/scripts/drupal-vm/configure-solr.sh
    - ../../../acquia/blt/scripts/drupal-vm/post-provision.php
